version: '3'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'java-postgres'
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_USER=omegalul'
      - 'POSTGRES_PASSWORD=newpassword'
      - 'POSTGRES_DB=mydb'

  app:
    build: ./
    container_name: 'java-app'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
